name: one_my_tasks
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  cached_network_image: ^3.3.1
  cloud_firestore: ^4.17.5
  country_flags: ^3.0.0
  firebase_auth: ^4.19.6
  firebase_core: ^2.31.1
  firebase_storage: ^11.7.6
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_localizations: 
    sdk: flutter
  form_validator: ^2.1.1
  http: ^1.2.1
  image_picker: ^1.1.1
  intl: any
  provider: ^6.1.2
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "images/list.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "images/list.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "images/list.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "images/list.png"




flutter:
  uses-material-design: true

  assets:
    - images/
    - languages/
